################################################################################
### GUAMAN AND TORRES-MARTINEZ (2023) - ON HOUSING MARKETS WITH INDECISIVE   ###
### AGENTS - SHINY APP BY NICOLAS LEIVA DIAZ - VERSION 1.0 OCTOBER 2023      ###
### NLEIVAD@FEN.UCHILE.CL - NS.LEIVA.D@GMAIL.COM                             ###
################################################################################

# THIS SCRIPT DEVELOP A FUNCTION THAT TAKES A LIST OF PREFERENCES, AND CHECK
# IF THEY ARE TRANSITIVE. UNDERSTANDING THAT A TRANSITIVITY PREFERENCE IS ONE
# WHERE IF A IS PREFERRED TO B AND B IS PREFERRED TO C, THEN A IS PREFERRED TO C
# THIS FUNCTION RETURN A STRING THAT INDICATES IS THE PREFERENCE IS TRANSITIVE.
# FIRST DEFINE THE FUNCTION WITH ONE INPUT, THE PREFERENCE TO BE CHECKED AS A
# LIST:
CheckTransitivity <- function(Preference){
  # EXTRACT THE PREFERENCES AND MAKE IT A MATRIX, EACH ROW OF THIS MATRIX IS
  # A PREFERENCE OVER A PAIR
  Pref <- matrix(unlist(Preference), ncol = 2, byrow = T)
  # DEFINE A VECTOR NAMED PROBLEMS THAT WILL POINT IF THERE IS PROBLEMS WITH THE
  # TRANSITIVITY
  Problem <- vector()
  # FOR EACH PREFERENCE (ROW)
  for (i in 1:nrow(Pref)) {
    # EXTRACT THE PREFERENCE (A,B) FROM THE MATRIX
    succ <- Pref[i,]
    # GET THE ROWS WHERE THE PREFERRED OPTION (A) OF THIS PREFERENCE ISN'T 
    # PREFERRED (IS IN THE SECOND COLUMN OR SECOND PLACE IN THAT ROW)
    Less <- Pref[which(Pref[,2] == succ[1]),]
    # IF THERE IS NO ROW WHERE THE OPTION ISN'T PREFERRED (A IS ALWAYS FIRST)
    if(length(Less) == 0){
      # GO TO THE NEXT PREFERENCE
      next
      # IN THE CASE WHERE IS ONLY ONE OTHER OPTION THAT IS PREFERRED (LET IT BE C)
      # THE LENGTH OF LESS OBJECT WILL BE 2 (C,A)
    } else if(length(Less) == 2){
      # HOW THERE IS AN OPTION PREFERRED (C), THE FIRST ELEMENT OF LIST WILL BE
      # THIS PREFERRED OPTION, CHECK THAT OPTION C ISN'T LESS PREFERRED THAN B,
      # THIS EQUALS TO CHECK IF THERE IS A ROW IN THE PREFERENCES MATRIX WHERE
      # B IS FIRST AND C SECOND. CHECK THIS GIVE BOOLEANS VALUES THAT EQUALS
      # 0 (FALSE) AND 1 (TRUE) FOR EACH ROW DEPENDING IF THE ROW MEETS THE
      # CONDITION. NOTE THAT IF ALL ROWS DOESN'T MEET THE CONDITION, THEN THERE
      # WILL BE ONLY FALSE AS BOOLEAN VALUES, AND HOW FALSE EQUALS 0, THE SUM
      # OF ALL THOSE BOOLEAN VALUES WILL BE 0 POINTING THAT THERE IS NO PROBLEM
      # WITH THE TRANSITIVITY. INSTEAD IF THERE IS ONE ROW WITH TRANSITIVITY
      # PROBLEMS, THE SUM WILL BE GREATER THAN 0
      if(sum((Pref[,1] == succ[2]) & (Pref[,2] == Less[1])) == 0){
        next
      } else {
        Problem <- append(Problem, "Problem")
      }
      # IN OTHER CASE WHERE THERE IS ROWS WHERE THE OPTION ISN'T PEFERRED, CHECK
      # THE SAME FOR EACH OPTION THAT IS PREFERRED
    } else {
      for (ii in 1:(length(Less)/2)) {
        succ_aux <- Less[ii,]
        # CHECK THE SAME THAT IN THE PREVIOUS CASE, FOR EACH C PREFERRED TO A,
        # CHECK IF THERE IS A ROW WHERE B IS PREFERRED TO C (REMEMBER THAT A WAS
        # PREFERRED TO C)
        if(sum((Pref[,1] == succ[2]) & (Pref[,2] == succ_aux[1])) == 0){
          next
        } else {
          Problem <- append(Problem, "Problem")
        }
      }
    }
  }
  if(length(Problem) == 0){
    return("Transitive")
  } else {
    return("Non Transitive")
  }
}