################################################################################
### GUAMAN AND TORRES-MARTINEZ (2023) - ON HOUSING MARKETS WITH INDECISIVE   ###
### AGENTS - SHINY APP BY NICOLAS LEIVA DIAZ - VERSION 1.0 OCTOBER 2023      ###
### NLEIVAD@FEN.UCHILE.CL - NS.LEIVA.D@GMAIL.COM                             ###
################################################################################

# THIS SCRIPT DEVELOP A FUNCTION THAT TAKES A LIST OF SCENARIOS CONTAINING THE
# DIFFERENT SCENARIOS WITH THE RESPECTIVE PREFERENCE MATRIX AND APPLY THE TOP
# TRADING CYCLES ALGORITHM IN ORDER TO GET THE CORE OF THE MARKET.
# THE IDEA IS TO GET AS OUTPUT A LIST CONTAINING ALL THE MATCHINGS THAT ARE IN
# THE CORE.
# FIRST IS DEFINED THE FUNCTION ALONG WITH ITS ARGUMENT
GetCore <- function(Scenarios){
  # DEFINE A LIST THAT WILL CONTAIN THE MATCHINGS RESULTING FROM APPLYING TOP
  # TRADING CYCLES ALGORITHM TO EACH PREFERENCE PROFILE/COMPLETION
  Core <- list()
  # FOR EACH SCENARIO
  for (s in 1:length(Scenarios)) {
    # GET THE PREFERENCE MATRIX
    P <- Scenarios[[paste0("Scenario_", s)]][["PrefMatrix"]]
    # APPLY TOP TRADING CYCLES ALGORITHM AND GET THE MATCHING AS A DATA FRAME
    # WITH THE FIRST COLUMN THE NUMBER OF THE AGENT AND THE SECOND COLUMN THE
    # HOUSE ASSIGNED UNDER THE TOP TRADING CYCLES ALGORITHM
    Mu <- data.frame(Agent = 1:nrow(P),
                     House = matrix(toptrading(pref = P)))
    # APPEND THIS MATCHING TO THE CORE SET
    Core <- append(Core, list(Mu))
    # IN ORDER TO OPTIMIZE MEMORY, CHECK THERE IS NO REPEATED MATCHINGS
    Core <- unique(Core)
  }
  return(Core)
}
